server:
  port: 8084
  servlet:
    context-path: /xt-demo

spring:
  datasource:
    username: root
    password: 1QAZ2wsx
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #      需要了解每项用法
      #监控统计拦截的过滤器 不加监控界面sql无法统计 wall用于防火墙
      filters: stat,wall,log4j,config
      #最大连接数
      max-active: 100
      #初始化大小
      initial-size: 1
      #获取连接最大等待时间 毫秒
      max-wait: 60000
      min-idle: 1
      #间隔多久检测一次需要关闭的空闲连接 毫秒
      time-between-eviction-runs-millis: 60000
      #连接在连接池中最小生存的时间，毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        url-pattern: /*
      stat-view-servlet:
        #白名单IP
        allow: 0.0.0.0
        #黑名单IP
        deny: 0.0.0.0
        #登录账号和密码
        login-username: admin
        login-password: admin
        #启用重置数据功能
        reset-enable: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true



  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5

web:
  upload-path: ‎/Users/mac/Desktop/xt/

mybatis:
  #  mapper 文件夹在resources 路径下时:
  mapper-locations: classpath:mapper/*.xml
  #  mapper 文件夹在package  com.xt 路径下时
  #  mapper-locations: classpath:mapper/*Mapper.xml
  #  mapper-locations: classpath:com/xt/mapper/*Mapper.xml
  type-aliases-package: com.xt.entity